# Example dbt_project.yml with best practices configuration

name: 'my_dbt_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  my_dbt_project:
    # Configuration for staging models
    staging:
      +materialized: view
      +docs:
        node_color: "lightblue"
      +meta:
        tier: "bronze"
        
    # Configuration for intermediate models  
    intermediate:
      +materialized: ephemeral
      +docs:
        node_color: "orange"
      +meta:
        tier: "silver"
        
    # Configuration for mart models
    marts:
      +materialized: table
      +docs:
        node_color: "green"
      +meta:
        tier: "gold"
      # Enable contracts for production models (dbt v1.5+)
      +contract:
        enforced: true

# Test configurations
tests:
  +store_failures: true
  +severity: error

# Snapshot configurations
snapshots:
  my_dbt_project:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at

# Seed configurations
seeds:
  my_dbt_project:
    +docs:
      node_color: "tan"
    +meta:
      tier: "bronze"

# Macro configurations
macros:
  my_dbt_project:
    +docs:
      node_color: "purple"

# Variables (can be overridden in profiles.yml or CLI)
vars:
  # Test-driven development settings
  enable_unit_tests: true
  require_unit_tests: true
  require_data_tests: true
  
  # Documentation requirements
  require_model_descriptions: true
  require_column_descriptions: true
  
  # Data quality settings
  test_severity: "error"  # error, warn
  
  # Performance settings
  max_batch_size: 1000
  
  # Environment-specific variables
  start_date: '2023-01-01'
  end_date: '2023-12-31'

# dbt v1.8+ specific configurations
flags:
  # Enable static parser for better performance
  static_parser: true
  
  # Enable unit test support
  enable_legacy_logger: false

# Dispatch configuration for package compatibility
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['my_dbt_project', 'dbt_utils']

# Query comment configuration
query-comment:
  comment: |
    dbt model: {{ node.unique_id }}
    dbt version: {{ dbt_version }}
    Invocation ID: {{ invocation_id }}
  append: true

# Incremental model configurations
incremental:
  on_schema_change: "fail"  # fail, ignore, sync_all_columns

# Documentation configuration
docs:
  include: "**/*"
  exclude: "dbt_packages/**/*"